import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './stylesheets/footer.css';
import './stylesheets/header.css';
import './globals.css';

import AppShell from './appshell';
import Footer from '@/components/footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'RUMANTISCHVIVO - Romanish Learning Website',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="it" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <div className="app-shell">
          <AppShell>
            <main className="app-main">{children}</main>
          </AppShell>

          <Footer />
        </div>
      </body>
    </html>
  );
}