// src/app/layout.tsx
import type { Metadata } from 'next';

// importa TUTTI i css globali QUI
import './globals.css';
import './stylesheets/header.css';
import './stylesheets/footer.css';

export const metadata: Metadata = {
  title: 'RUMANTISCHVIVO - Romanish Learning Website',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="it">
      <body>{children}</body>
    </html>
  );
}